### the following notebook takes as an input the vt_cleaned_sentiment.csv with the results of the sentiment analysis and merge data regarding cases and deaths due to covid.

### For the merge the time range considered is from 2020-12-12 to 2021-03-14

In [1]:
# libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
!ls

Data                                   merge_cases_deaths_complete.ipynb
Sentiment Analysis Covid Vaccine.ipynb merge_events.ipynb
geopy_location_mapping.ipynb           sentiment analysis code
merge_cases_deaths.ipynb

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
# dataframe
df       =  pd.read_csv("Data/vt_cleaned_sentiment_with_country.csv")  
cas_dea  = pd.read_csv("Data/daily-covid-cases-deaths.csv")

In [5]:
df.head()

,Unnamed: 0,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment
0,9,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12 19:30:33,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral
1,12,1337815730486702087,WION,India,#WION: World Is One | Welcome to India’s first...,2016-03-21 03:44:54,292510,91,7531,True,2020-12-12 17:45:00,The agency also released new information for h...,NaN,TweetDeck,0,18,False,"[78.6677428, 22.3511148]","22.3511148, 78.6677428",India,The agency also released new information for h...,0.136364,positive
2,17,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12 15:38:00,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive
3,30,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12 14:04:37,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive
4,44,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12 11:55:28,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral

In [6]:
df = df.dropna()

In [7]:
# requires strictly string, nan are class float
# will produce an error
for line in df['date']:
  if type(line) == float:
    print(line)
    break
print('no na')

no na

In [8]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [9]:
df.head()

,Unnamed: 0,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment
0,9,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral
2,17,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive
3,30,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive
4,44,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral
5,45,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral

In [10]:
# range date column
df.dtypes

Unnamed: 0            object
id                    object
user_name             object
user_location         object
user_description      object
user_created          object
user_followers        object
user_friends          object
user_favourites       object
user_verified         object
date                  object
text                  object
hashtags              object
source                object
retweets              object
favorites             object
is_retweet            object
user_coordinates      object
user_coordinates2     object
user_country          object
modified_text         object
sent_score           float64
sentiment             object
dtype: object

In [11]:
# requires strictly string, nan are class float
# will produce an error
df = df.dropna()

In [12]:
# requires strictly string, nan are class float
# will produce an error
for line in df['date']:
  if type(line) == float:
    print(line)
    break
print('no na')

no na

In [13]:
df.date = pd.to_datetime(df.date, format='%Y-%m-%d')

In [14]:
df.dtypes

Unnamed: 0                   object
id                           object
user_name                    object
user_location                object
user_description             object
user_created                 object
user_followers               object
user_friends                 object
user_favourites              object
user_verified                object
date                 datetime64[ns]
text                         object
hashtags                     object
source                       object
retweets                     object
favorites                    object
is_retweet                   object
user_coordinates             object
user_coordinates2            object
user_country                 object
modified_text                object
sent_score                  float64
sentiment                    object
dtype: object

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.sort_values(by='date').tail()

,Unnamed: 0,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment
11357,65355,1385058720271327233,K.C. Ramamurthy,Bangalore,"Member of Parliament, Rajyasabha (Karnataka) |...",2020-07-15 10:56:08,336,283,995,False,2021-04-22,"Vaccination Works Incredibly Well, Data Show i...",['LargestVaccineDrive'],Twitter for Android,0,0,False,"[77.5912997, 12.9791198]","12.9791198, 77.5912997",India,"Vaccination Works Incredibly Well, Data Show i...",1.000000,positive
11358,65361,1385055253649936385,Hindustan Times,India,One of India's largest media companies. Latest...,2009-04-29 10:11:34,7959130,129,2929,True,2021-04-22,#Covaxin's efficacy of 78% was recorded agains...,"['Covaxin', 'Covid19']",TweetDeck,3,21,False,"[78.6677428, 22.3511148]","22.3511148, 78.6677428",India,#Covaxin's efficacy of 78% was recorded agains...,0.166667,positive
11359,65380,1385043173949415429,IndiaToday,India,"Brings you news breaks: Exclusive political, e...",2009-02-02 07:21:54,5604583,250,4438,True,2021-04-22,The result showed that #Covaxin's efficacy aga...,"['Covaxin', 'RE']",TweetDeck,6,28,False,"[78.6677428, 22.3511148]","22.3511148, 78.6677428",India,The result showed that #Covaxin's efficacy aga...,0.000000,neutral
11947,68039,1385097630628384768,Nairobi_Exposed,Kenya,Media,2021-04-09 08:04:42,1212,457,138,False,2021-04-22,@PrinceD57219228 @praj21582761 Some bad adviso...,['agakhanandnmgcartels'],Twitter Web App,0,0,False,"[38.4313975, 1.4419683]","1.4419683, 38.4313975",Kenya,@PrinceD57219228 @praj21582761 Some bad adviso...,-0.700000,negative
10958,61942,1385060833827295237,Ketan,India,Political & Social Analyst. Privileged to have...,2009-03-27 08:22:14,8231,181,34119,False,2021-04-22,#COVID19 Private hospital chains in talks to o...,"['COVID19', 'COVIDVaccines', 'PfizerVaccine', ...",Twitter for Android,0,0,False,"[78.6677428, 22.3511148]","22.3511148, 78.6677428",India,#COVID19 Private hospital chains in talks to o...,0.000000,neutral

In [17]:
# range between 2020-12-12 and 2021-04-22

In [18]:
cas_dea.head(50)

,Entity,Code,Day,Daily new confirmed cases of COVID-19,Daily new confirmed deaths due to COVID-19
0,Afghanistan,AFG,2020-02-24,1.0,NaN
1,Afghanistan,AFG,2020-02-25,0.0,NaN
2,Afghanistan,AFG,2020-02-26,0.0,NaN
3,Afghanistan,AFG,2020-02-27,0.0,NaN
4,Afghanistan,AFG,2020-02-28,0.0,NaN
5,Afghanistan,AFG,2020-02-29,0.0,NaN
6,Afghanistan,AFG,2020-03-01,0.0,NaN
7,Afghanistan,AFG,2020-03-02,0.0,NaN
8,Afghanistan,AFG,2020-03-03,1.0,NaN
9,Afghanistan,AFG,2020-03-04,2.0,NaN
10,Afghanistan,AFG,2020-03-05,0.0,NaN
11,Afghanistan,AFG,2020-03-06,0.0,NaN
12,Afghanistan,AFG,2020-03-07,0.0,NaN
13,Afghanistan,AFG,2020-03-08,1.0,NaN
14,Afghanistan,AFG,2020-03-09,2.0,NaN
15,Afghanistan,AFG,2020-03-10,1.0,NaN
16,Afghanistan,AFG,2020-03-11,3.0,NaN
17,Afghanistan,AFG,2020-03-12,1.0,NaN
18,Afghanistan,AFG,2020-03-13,1.0,NaN
19,Afghanistan,AFG,2020-03-14,2.0,NaN
20,Afghanistan,AFG,2020-03-15,1.0,NaN
21,Afghanistan,AFG,2020-03-16,2.0,NaN
22,Afghanistan,AFG,2020-03-17,2.0,NaN
23,Afghanistan,AFG,2020-03-18,4.0,NaN
24,Afghanistan,AFG,2020-03-19,1.0,NaN
25,Afghanistan,AFG,2020-03-20,4.0,NaN
26,Afghanistan,AFG,2020-03-21,1.0,NaN
27,Afghanistan,AFG,2020-03-22,4.0,1.0
28,Afghanistan,AFG,2020-03-23,7.0,0.0
29,Afghanistan,AFG,2020-03-24,2.0,0.0
30,Afghanistan,AFG,2020-03-25,33.0,1.0
31,Afghanistan,AFG,2020-03-26,4.0,1.0
32,Afghanistan,AFG,2020-03-27,11.0,0.0
33,Afghanistan,AFG,2020-03-28,16.0,1.0
34,Afghanistan,AFG,2020-03-29,11.0,0.0
35,Afghanistan,AFG,2020-03-30,28.0,0.0
36,Afghanistan,AFG,2020-03-31,29.0,0.0
37,Afghanistan,AFG,2020-04-01,22.0,0.0
38,Afghanistan,AFG,2020-04-02,43.0,0.0
39,Afghanistan,AFG,2020-04-03,35.0,4.0
40,Afghanistan,AFG,2020-04-04,25.0,2.0
41,Afghanistan,AFG,2020-04-05,38.0,2.0
42,Afghanistan,AFG,2020-04-06,30.0,3.0
43,Afghanistan,AFG,2020-04-07,56.0,1.0
44,Afghanistan,AFG,2020-04-08,21.0,0.0
45,Afghanistan,AFG,2020-04-09,40.0,1.0
46,Afghanistan,AFG,2020-04-10,47.0,1.0
47,Afghanistan,AFG,2020-04-11,24.0,0.0
48,Afghanistan,AFG,2020-04-12,52.0,1.0
49,Afghanistan,AFG,2020-04-13,58.0,3.0

In [19]:
cases  = cas_dea[['Day', 'Daily new confirmed cases of COVID-19']]
deaths = cas_dea[['Day', 'Daily new confirmed deaths due to COVID-19']]
cases.columns  = ['Date', 'Daily new confirmed cases of COVID-19']
deaths.columns = ['Date', 'Daily new confirmed deaths due to COVID-19']

In [20]:
# on the cases
cases = cases.groupby(by=["Date"]).sum()
cases.reset_index(level=0, inplace=True)
cases.head()

         Date  Daily new confirmed cases of COVID-19
0  2020-01-22                                    0.0
1  2020-01-23                                  411.0
2  2020-01-24                                 1175.0
3  2020-01-25                                 2004.0
4  2020-01-26                                 2803.0

In [21]:
type(cases)
#cases.date = cases.to_datetime(cases.date, format='%Y-%m-%d')
#cases.dtypes

pandas.core.frame.DataFrame

In [22]:
cases.Date = pd.to_datetime(cases.Date, format='%Y-%m-%d')

In [23]:
cases.sort_values(by='Date').head()

        Date  Daily new confirmed cases of COVID-19
0 2020-01-22                                    0.0
1 2020-01-23                                  411.0
2 2020-01-24                                 1175.0
3 2020-01-25                                 2004.0
4 2020-01-26                                 2803.0

In [24]:
cases.sort_values(by='Date').tail()

          Date  Daily new confirmed cases of COVID-19
486 2021-05-22                              4401278.0
487 2021-05-23                              3656636.0
488 2021-05-24                              3482499.0
489 2021-05-25                              4045310.0
490 2021-05-26                              4251903.0

In [25]:
deaths = deaths.groupby(by=["Date"]).sum()
deaths.reset_index(level=0, inplace=True)
deaths.Date = pd.to_datetime(deaths.Date, format='%Y-%m-%d')
deaths.sort_values(by='Date').head()

        Date  Daily new confirmed deaths due to COVID-19
0 2020-01-22                                         0.0
1 2020-01-23                                         4.0
2 2020-01-24                                        32.0
3 2020-01-25                                        64.0
4 2020-01-26                                        56.0

In [26]:
deaths.sort_values(by='Date').tail()

          Date  Daily new confirmed deaths due to COVID-19
486 2021-05-22                                     85207.0
487 2021-05-23                                     72901.0
488 2021-05-24                                     67103.0
489 2021-05-25                                     95834.0
490 2021-05-26                                     94744.0

In [27]:
# df time range available  2020-12-12 and 2021-04-22
# cases time range available 2020-01-23	 to 2021-03-14	
# deaths time range available 2020-01-23	to 2021-03-14	


### FOR THE MERGE CONSIDER THE RANGE 2020-12-12 TO 2021-03-14

In [28]:
def filter_date_range(data, string_name_column_date):
    
    start_date = "2020-12-12"
    end_date = "2021-04-22"

    after_start_date = data[string_name_column_date] >= start_date
    before_end_date = data[string_name_column_date] <= end_date
    between_two_dates = after_start_date & before_end_date
    filtered_dates = data.loc[between_two_dates]
    
    return filtered_dates

In [29]:
filt_df = filter_date_range(df, 'date')
filt_cases = filter_date_range(cases, 'Date')
filt_deaths = filter_date_range(deaths, 'Date')

In [30]:
### FOR THE MERGE CONSIDER THE RANGE 2020-12-12 TO 2021-03-14
filt_df.date.head(1)

0   2020-12-12
Name: date, dtype: datetime64[ns]

In [31]:
filt_df.date.tail(1)

12227   2021-04-14
Name: date, dtype: datetime64[ns]

In [32]:
### FOR THE MERGE CONSIDER THE RANGE 2020-12-12 TO 2021-03-14
filt_cases.Date.head(1)

325   2020-12-12
Name: Date, dtype: datetime64[ns]

In [33]:
filt_cases.Date.tail(1)

456   2021-04-22
Name: Date, dtype: datetime64[ns]

In [34]:
### FOR THE MERGE CONSIDER THE RANGE 2020-12-12 TO 2021-03-14
filt_deaths.Date.head(1)

325   2020-12-12
Name: Date, dtype: datetime64[ns]

In [35]:
filt_deaths.head()

          Date  Daily new confirmed deaths due to COVID-19
325 2020-12-12                                     78057.0
326 2020-12-13                                     55661.0
327 2020-12-14                                     68538.0
328 2020-12-15                                    103882.0
329 2020-12-16                                    101136.0

In [36]:
filt_deaths.Date.tail(1)

456   2021-04-22
Name: Date, dtype: datetime64[ns]

In [37]:
filt_cases.columns = ['date', 'Daily new confirmed cases of COVID-19']
filt_cases

          date  Daily new confirmed cases of COVID-19
325 2020-12-12                              4675036.0
326 2020-12-13                              3913949.0
327 2020-12-14                              3852575.0
328 2020-12-15                              4698877.0
329 2020-12-16                              5398641.0
..         ...                                    ...
452 2021-04-18                              5294163.0
453 2021-04-19                              5330654.0
454 2021-04-20                              6571264.0
455 2021-04-21                              6847949.0
456 2021-04-22                              6925425.0

[132 rows x 2 columns]

In [38]:
filt_df.shape

(9340, 23)

In [39]:
filt_df.head()

,Unnamed: 0,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment
0,9,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral
2,17,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive
3,30,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive
4,44,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral
5,45,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral

In [40]:
filt_df['cases'] = 0
filt_df.reset_index(level=0, inplace=True)
del filt_df['Unnamed: 0']
del filt_df['index']
filt_df.head()

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment,cases
0,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral,0
1,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive,0
2,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive,0
3,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral,0
4,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral,0

In [41]:
'''
for index, row in df.iterrows():
    while True:
        try:
            #print(row)
            #print(row.date)
            temp = filt_cases.loc[filt_cases['Date'] == row.date]
            #print(temp.iloc[0])
            #print(temp.iloc[0]['Daily new confirmed cases of COVID-19'])
            #print(type(temp))
            #sub_df.iloc[0]['A']
            #df.iloc[index]['cases'] = temp.iloc[0]['Daily new confirmed cases of COVID-19']
            #print(temp.iloc[0]['Daily new confirmed cases of COVID-19'])
            df['cases'][index] = temp.iloc[0]['Daily new confirmed cases of COVID-19']
            #df.iloc[index].loc['cases'] = temp.iloc[0]['Daily new confirmed cases of COVID-19']
        except ValueError:
            print(row)
            break
'''

"\nfor index, row in df.iterrows():\n    while True:\n        try:\n            #print(row)\n            #print(row.date)\n            temp = filt_cases.loc[filt_cases['Date'] == row.date]\n            #print(temp.iloc[0])\n            #print(temp.iloc[0]['Daily new confirmed cases of COVID-19'])\n            #print(type(temp))\n            #sub_df.iloc[0]['A']\n            #df.iloc[index]['cases'] = temp.iloc[0]['Daily new confirmed cases of COVID-19']\n            #print(temp.iloc[0]['Daily new confirmed cases of COVID-19'])\n            df['cases'][index] = temp.iloc[0]['Daily new confirmed cases of COVID-19']\n            #df.iloc[index].loc['cases'] = temp.iloc[0]['Daily new confirmed cases of COVID-19']\n        except ValueError:\n            print(row)\n            break\n"

In [42]:
for index, row in filt_df.iterrows():
    filt_df.loc[index,'cases'] = filt_cases.loc[filt_cases['date'] == row.date].iloc[0]['Daily new confirmed cases of COVID-19']

In [43]:
filt_df.head()

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment,cases
0,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral,4675036.0
1,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive,4675036.0
2,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive,4675036.0
3,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral,4675036.0
4,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral,3906009.0

In [44]:
filt_deaths.head()

          Date  Daily new confirmed deaths due to COVID-19
325 2020-12-12                                     78057.0
326 2020-12-13                                     55661.0
327 2020-12-14                                     68538.0
328 2020-12-15                                    103882.0
329 2020-12-16                                    101136.0

In [45]:
filt_df.shape

(9340, 23)

In [46]:
filt_deaths.columns = ['date', 'Daily new confirmed deaths due to COVID-19']
filt_deaths

          date  Daily new confirmed deaths due to COVID-19
325 2020-12-12                                     78057.0
326 2020-12-13                                     55661.0
327 2020-12-14                                     68538.0
328 2020-12-15                                    103882.0
329 2020-12-16                                    101136.0
..         ...                                         ...
452 2021-04-18                                     64935.0
453 2021-04-19                                     79137.0
454 2021-04-20                                    105818.0
455 2021-04-21                                    105465.0
456 2021-04-22                                    102643.0

[132 rows x 2 columns]

In [47]:
filt_df

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment,cases
0,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral,4675036.0
1,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive,4675036.0
2,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive,4675036.0
3,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral,4675036.0
4,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral,3906009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9335,1382253724878344196,Roopam,Ranchi,Be Ur Kind of Crazy....Someone out there will ...,2019-08-19 14:55:44,304,280,87,False,2021-04-14,Mr. @RahulGandhi it is not because of you but ...,['SputnikV'],Twitter Web App,0,2,False,"[85.3250132, 23.3700354]","23.3700354, 85.3250132",India,Mr. @RahulGandhi it is not because of you but ...,0.000000,neutral,6243243.0
9336,1382250817189597189,moneycontrol,Mumbai,Moneycontrol is India’s No. 1 financial portal...,2009-08-26 07:55:29,1077795,297,1079,True,2021-04-14,.@viswanath_pilla looks at how #SputnikV stack...,"['SputnikV', 'Covishield', 'Covaxin']",Twitter Web App,2,4,False,"[72.8773928, 19.0759899]","19.0759899, 72.8773928",India,.@viswanath_pilla looks at how #SputnikV stack...,0.000000,neutral,6243243.0
9337,1382250738760384515,ET NOW,India,Youtube: https://t.co/u54RR8zcQ8 Facebook: htt...,2010-12-10 12:49:29,641608,79,3,True,2021-04-14,Watch @drreddys address #SputnikV EUA #LIVE h...,"['SputnikV', 'LIVE']",Twitter Media Studio,1,10,False,"[78.6677428, 22.3511148]","22.3511148, 78.6677428",India,Watch @drreddys address #SputnikV EUA #LIVE h...,0.136364,positive,6243243.0
9338,1382248484259123205,Russian Mission in Geneva,Geneve,Постпредство России при Отделении ООН и др. ме...,2011-07-26 08:40:47,9862,589,3502,True,2021-04-14,✅ 🇷🇺#Gamaleya Research Center in cooperation w...,['Gamaleya'],Twitter for iPhone,2,9,False,"[6.1466014, 46.2017559]","46.2017559, 6.1466014",Switzerland,✅ 🇷🇺#Gamaleya Research Center in cooperation w...,-0.100000,negative,6243243.0
9339,1382246393532801026,Mora Mosese,NtswanaTsatsi,#MoAfrika - #MoSotho,2019-12-06 11:11:07,164,101,6465,False,2021-04-14,@FloydShivambu #SputnikV. Where are #AfricanEx...,"['SputnikV', 'AfricanExpertise', 'ShamDemic']",Twitter Web App,0,0,False,"[28.8554121, -27.2286065]","-27.2286065, 28.8554121",South Africa,@FloydShivambu #SputnikV. Where are #AfricanEx...,0.100000,positive,6243243.0

In [48]:
filt_df['deaths'] = 0
filt_df.head()

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment,cases,deaths
0,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral,4675036.0,0
1,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive,4675036.0,0
2,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive,4675036.0,0
3,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral,4675036.0,0
4,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral,3906009.0,0

In [49]:
for index, row in filt_df.iterrows():
    filt_df.loc[index,'deaths'] = filt_deaths.loc[filt_deaths['date'] == row.date].iloc[0]['Daily new confirmed deaths due to COVID-19']

In [50]:
filt_df.head()

,id,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,retweets,favorites,is_retweet,user_coordinates,user_coordinates2,user_country,modified_text,sent_score,sentiment,cases,deaths
0,1337842295857623042,Ch.Amjad Ali,Islamabad,#ProudPakistani #LovePakArmy #PMIK @insafiansp...,2012-11-12 04:18:12,671,2368,20469,False,2020-12-12,#CovidVaccine \n\nStates will start getting #C...,"['CovidVaccine', 'COVID19Vaccine', 'US', 'paku...",Twitter Web App,0,0,False,"[73.0651511, 33.6938118]","33.6938118, 73.0651511",Pakistan,#CovidVaccine \n\nStates will start getting #C...,0.000000,neutral,4675036.0,78057.0
1,1337783770070409218,ILKHA,Türkiye,Official Twitter account of Ilke News Agency /,2015-05-22 08:31:12,4056,6,3,True,2020-12-12,"Coronavirus: Iran reports 8,201 new cases, 221...","['Iran', 'coronavirus', 'PfizerBioNTech']",TweetDeck,3,5,False,"[34.9249653, 38.9597594]","38.9597594, 34.9249653",Turkey,"Coronavirus: Iran reports 8,201 new cases, 221...",0.068182,positive,4675036.0,78057.0
2,1337760271151063040,Andy Thomas,London,Retweets not necessarily endorsements.,2009-03-07 20:39:15,1151,4301,95963,False,2020-12-12,"@ZubyMusic 6 deaths so far. \nIt's only death,...","['CovidVaccines', 'Pfizervaccine']",Twitter for Android,0,2,False,"[-0.1276474, 51.5073219]","51.5073219, -0.1276474",United Kingdom,"@ZubyMusic 6 deaths so far. \nIt's only death,...",0.050000,positive,4675036.0,78057.0
3,1337727767551553536,Daily News Egypt,Egypt,Egypt's Only Daily Independent Newspaper in En...,2009-04-26 07:56:24,278080,116,765,True,2020-12-12,#FDA authorizes #PfizerBioNTech #coronavirus v...,"['FDA', 'PfizerBioNTech', 'coronavirus']",Twitter Web App,1,1,False,"[29.2675469, 26.2540493]","26.2540493, 29.2675469",Egypt,#FDA authorizes #PfizerBioNTech #coronavirus v...,0.000000,neutral,4675036.0,78057.0
4,1340571472025141248,IP_Man,America,"One Man, \nWith One Statistically Impossible G...",2012-06-21 01:41:33,625,477,14475,False,2020-12-20,When The #CovidVaccine \nPoisons Enough Of The...,"['CovidVaccine', 'BellsPalsy']",Twitter Web App,0,0,False,"[5.9799001, 51.4371483]","51.4371483, 5.9799001",Netherlands,When The #CovidVaccine \nPoisons Enough Of The...,0.000000,neutral,3906009.0,58657.0

In [51]:
filt_df.to_csv('Data/vt_cases_deaths_complete.csv', index = False)